---
title: "Generating XPEB_Document"
author: "Peter Fiorica"
date: "July 3, 2019"
output: html_document
---


```{r}
library(data.table)
library(dplyr)
"%&%" = function(a,b) paste(a,b,sep="")

brain_tissues<-c('Brain_Anterior_cingulate_cortex_BA24', 'Brain_Caudate_basal_ganglia', 'Brain_Cerebellar_Hemisphere', 'Brain_Cerebellum', 'Brain_Cortex','Brain_Frontal_Cortex_BA9', 'Brain_Hippocampus', 'Brain_Hypothalamus', 'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia')

genenames<-fread("Z://PrediXcan/BP_Chrome.txt",header =T)

XPEB_total<-fread("Z://AA_nonGAIN_SCZ/PeerJReviews/XPEB/output/s_prediXcan_scz_fullresults.txt", header =T)

for (i in brain_tissues){
  one<-fread("Z://AA_nonGAIN_SCZ/PrediXcan/output/1000G/1000GTW_"%&% i %&%"_0.5.db_association.txt", header = T)
  one$tissue<-i
  if(exists("predixcan_results")){
    predixcan_results<-bind_rows(predixcan_results,one)
  }else{
    predixcan_results<-one
  }
}
flags<-fread("Z://PrediXcan/flags.txt", header=T)
gtex6Wflags<-left_join(predixcan_results,flags, by= c("gene","tissue"="model"))

row.has.naflags <- apply(gtex6Wflags, 1, function(x){any(is.na(x))})
sum(row.has.naflags)
newgtex6vflags<-gtex6Wflags[!row.has.naflags,]

noredflags<-newgtex6vflags[!(newgtex6vflags$flag=="red"),]
predixcan_results<-noredflags[!(noredflags$flag=="yellow"),]

predixcan_results<-left_join(predixcan_results,genenames, by=c("gene"))

#dlpfc_pred<-fread("Z://AA_nonGAIN_SCZ/PrediXcan/output/1000G/Brain/1000G_association.txt", header =T)
#dlpfc_pred$tissue<-"DLPC"
#dlpfc_pred<-left_join(dlpfc_pred,genenames, by=c("gene"))

#predixcan_results<-bind_rows(predixcan_results, dlpfc_pred)



titles_pred_results<-dplyr::select(predixcan_results, genename, CHR, BP, p, tissue)
gene.has.na<-apply(titles_pred_results, 1, function(x){any(is.na(x))})
titles_pred_results<-titles_pred_results[!gene.has.na,]
titles_pred_results<-mutate(titles_pred_results, SNP=paste(genename,sep = "---",tissue)) #This is the file that is used for combined Brain XPEB

file2write<-dplyr::select(titles_pred_results, SNP, CHR, BP, p)
colnames(file2write)<-c("SNP", "CHR", "BP", "P")
fwrite(file2write, "Z://AA_nonGAIN_SCZ/PeerJReviews/XPEB/spredixcan_scz_prep/target_braincombined.txt", col.names = T, quote =F, row.names = F, sep = " ")
```
Above, we just created the all brain input (target) file for XPEB


```{r}
for (tis in brain_tissues){
  two<-fread("Z://AA_nonGAIN_SCZ/PGC_SCZ_Summary_Stats/SPrediXcan_Results/TW_" %&% tis %&%"_S-PrediXcan_Results_SCZ.txt", header = T)
  two$tissue<-tis
  if(exists("spredixcan_results")){
    spredixcan_results<-bind_rows(spredixcan_results,two)
  }else{
    spredixcan_results<-two
    }
}

gtex6Wflags<-left_join(spredixcan_results,flags, by= c("gene","tissue"="model"))
row.has.naflags <- apply(gtex6Wflags, 1, function(x){any(is.na(x))})
sum(row.has.naflags)
newgtex6vflags<-gtex6Wflags[!row.has.naflags,]
noredflags<-newgtex6vflags[!(newgtex6vflags$flag=="red"),]
spredixcan_results<-noredflags[!(noredflags$flag=="yellow"),]

#dlpfc_spred<-fread("Z://AA_nonGAIN_SCZ/PGC_SCZ_Summary_Stats/SPrediXcan_Results/DLPFC_sPrediXcan_Results_SCZ.txt", header =T)
#dlpfc_spred$tissue<-"DLPFC"
#dlpfc_spred<-left_join(dlpfc_spred,genenames, by ="gene")
#dlpfc_spred<-dplyr::select(dlpfc_spred,"gene","gene_name.y","zscore","effect_size","pvalue","var_g", "pred_perf_r2", "pred_perf_pval","pred_perf_qval","n_snps_used", "n_snps_in_cov","n_snps_in_model", "tissue")

#colnames(dlpfc_spred)<-c("gene","gene_name","zscore","effect_size","pvalue","var_g", "pred_perf_r2", "pred_perf_pval","pred_perf_qval","n_snps_used", "n_snps_in_cov","n_snps_in_model", "tissue")
#spredixcan_results<-bind_rows(spredixcan_results, dlpfc_spred)

spred_results<-dplyr::select(spredixcan_results,gene_name,pvalue,tissue)
spred_results<-mutate(spred_results,SNP=paste(gene_name,sep="---",tissue))
spred2write<-dplyr::select(spred_results,SNP,pvalue)
colnames(spred2write)<-c("SNP", "P")
fwrite(spred2write, "Z://AA_nonGAIN_SCZ/PeerJReviews/XPEB/spredixcan_scz_prep/base_braincombined.txt", col.names = T, quote =F, row.names = F, sep = " ")

```
Above, we made the input (base) file for XPEB

Below, we are making a master file of the XPEB,PrediXcan, and S-PrediXcan results across genes and tissues.
```{r}
GAINandPGC<-left_join(predixcan_results,spredixcan_results, by = c("gene", "tissue"))
brainsonly<-fread("Z://AA_nonGAIN_SCZ/PeerJReviews/XPEB/output/spredixcan_xpeb_output/braincombined_scz_xpeb_results.txt", header =T)


brainsonly2 <- separate(brainsonly, SNP, into = c("GENE","TISSUE"), sep = "---")
GAINandPGC<-dplyr::select(GAINandPGC,gene_name.x,CHR,BP,tissue,gene,p,pvalue,t,zscore,beta,effect_size)
colnames(GAINandPGC)<-c('GENE','CHR','BP','TISSUE','ENSG','P_pX','P_SpX','T_pX','Z_SpX','BETA_pX','BETA_SpX')

GAINandPGC2<-left_join(GAINandPGC,brainsonly2, by = c("GENE","TISSUE", "BP"))
GAINandPGC2<-dplyr::select(GAINandPGC2,'GENE','CHR.x','BP','TISSUE','ENSG','P_pX','P_SpX','T_pX','Z_SpX','BETA_pX','BETA_SpX','LOCFDR')

colnames(GAINandPGC2)<-c('GENE','CHR','BP','TISSUE','ENSG','P_pX','P_SpX','T_pX','Z_SpX','BETA_pX','BETA_SpX','LOCFDR_all')
GAINandPGC3<-left_join(XPEB_total,GAINandPGC2,by =c('SNP'='GENE','tissue'='TISSUE'))
row.has.na3 <- apply(GAINandPGC3, 1, function(x){any(is.na(x))})
sum(row.has.na3)
GAINandPGC3<-GAINandPGC3[!row.has.na3,]
GAINandPGC2write<-dplyr::select(GAINandPGC3,'SNP','CHR.x','BP.x','tissue','ENSG','P_pX','P_SpX','T_pX','Z_SpX','BETA_pX','BETA_SpX','LOCFDR_all','LOCFDR')
colnames(GAINandPGC2write)<-c('GENE','CHR','BP','TISSUE','ENSG','P_pX','P_SpX','T_pX','Z_SpX','BETA_pX','BETA_SpX','LOCFDR_all', 'LOCFDR_indep')

fwrite(GAINandPGC2write,"Z://AA_nonGAIN_SCZ/PeerJReviews/XPEB/total_xpeb_table.txt", col.names=T, row.names=F, quote =F, sep ="\t")
```