---
title: "Ashr_Prep_gtex7"
author: "Peter Fiorica"
date: "July 16, 2019"
output: html_document
---

```{r}
library(data.table)
library(dplyr)

"%&%" = function(a,b) paste(a,b,sep="")

brain_tissues<-c('Brain_Anterior_cingulate_cortex_BA24', 'Brain_Caudate_basal_ganglia', 'Brain_Cerebellar_Hemisphere', 'Brain_Cerebellum', 'Brain_Cortex','Brain_Frontal_Cortex_BA9', 'Brain_Hippocampus', 'Brain_Hypothalamus', 'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia')

genenames<-fread("Z://PrediXcan/BP_Chrome.txt",header =T)
```

```{r}
for (i in brain_tissues){
  one<-fread("Z://AA_nonGAIN_SCZ/PrediXcan/output/1000G/v7_GTEx/1000G_gtex_v7_"%&% i %&%"_imputed_europeans_tw_0.5_signif.db_association.txt", header = T)
  one$tissue<-i
  if(exists("predixcan_results")){
    predixcan_results<-bind_rows(predixcan_results,one)
  }else{
    predixcan_results<-one
  }
}
```

```{r}
library(ashr)
ash_pX_half_uni <- ash(predixcan_results$beta, predixcan_results$`se(beta)`, mixcompdist = 'halfuniform', method='fdr')

scz <- mutate(predixcan_results, ash_halfuni_pX=ash_pX_half_uni$result$lfdr)
fwrite(scz,"z://AA_nonGAIN_SCZ/PeerJReviews/gtex7_brain_ashr_results.txt", col.names=T, row.names=F, quote =F, sep = "\t")

```
The lowest lfsr was about 0.82


```{r}
GTEv7.1<-fread("Z://PrediXcan/tissuelistV7",header =F)
GTEv7.1$V1<-gsub("^.*?_","",GTEv7.1$V1)
GTEv7.1$V1<-gsub("^.*?_","",GTEv7.1$V1)
GTEv7.1$V1<-gsub(".{35}$","",GTEv7.1$V1)
GTEv7<-GTEv7.1$V1

for (i in GTEv7){
  one<-fread("Z://AA_nonGAIN_SCZ/PrediXcan/output/1000G/v7_GTEx/1000G_gtex_v7_"%&% i %&%"_imputed_europeans_tw_0.5_signif.db_association.txt", header = T)
  one$tissue<-i
  if(exists("predixcan_results1")){
    predixcan_results1<-bind_rows(predixcan_results1,one)
  }else{
    predixcan_results1<-one
  }
}

ash_pX_half_uni1 <- ash(predixcan_results1$beta, predixcan_results1$`se(beta)`, mixcompdist = 'halfuniform', method='fdr')

scz <- mutate(predixcan_results1, ash_halfuni_pX=ash_pX_half_uni1$result$lfdr)

scz<-scz %>%
  arrange(ash_halfuni_pX)


fwrite(scz,"z://AA_nonGAIN_SCZ/PeerJReviews/gtex7_all_ashr_results.txt", col.names=T, row.names=F, quote =F, sep = "\t")
```

Alright, now we can run ashr on the bipolar data results.

```{r}

for (i in GTEv7){
  one<-fread("Z://bipolar_disorder/predixcan/output/GTEx_V7/1000G_BP_V7_correctphenogtex_v7_"%&% i %&%"_imputed_europeans_tw_0.5_signif.db_association.txt", header = T)
  one$tissue<-i
  if(exists("predixcan_resultsbd")){
    predixcan_resultsbd<-bind_rows(predixcan_resultsbd,one)
  }else{
    predixcan_resultsbd<-one
  }
}

ash_pX_half_uni_bd <- ash(predixcan_resultsbd$beta, predixcan_resultsbd$`se(beta)`, mixcompdist = 'halfuniform', method='fdr')

bd <- mutate(predixcan_resultsbd, ash_halfuni_pX=ash_pX_half_uni_bd$result$lfdr)

bd<-bd %>%
  arrange(ash_halfuni_pX)

fwrite(bd,"Z://AA_nonGAIN_SCZ/PeerJReviews/bipolar_disorder_gtex7_all_ashr_results.txt", col.names = T, row.names = F, sep = "\t", quote = F)
```

In brain tissues alone:
```{r}

for (i in brain_tissues){
  one<-fread("Z://bipolar_disorder/predixcan/output/GTEx_V7/1000G_BP_V7_correctphenogtex_v7_"%&% i %&%"_imputed_europeans_tw_0.5_signif.db_association.txt", header = T)
  one$tissue<-i
  if(exists("predixcan_resultsbd1")){
    predixcan_resultsbd1<-bind_rows(predixcan_resultsbd1,one)
  }else{
    predixcan_resultsbd1<-one
  }
}

ash_pX_half_uni_bd1 <- ash(predixcan_resultsbd1$beta, predixcan_resultsbd1$`se(beta)`, mixcompdist = 'halfuniform', method='fdr')

bd1 <- mutate(predixcan_resultsbd1, ash_halfuni_pX=ash_pX_half_uni_bd1$result$lfdr)

bd1<-bd1 %>%
  arrange(ash_halfuni_pX)

```
