---
title: "PrediXcanGenePValuesForLoop"
author: "Peter Fiorica"
date: "2/12/2018"
output: html_document
---

```{r}
library(data.table)
"%&%" = function(a,b) paste(a,b,sep="")
database_tissues <- c("TW_Adipose_Subcutaneous_0.5.db", "TW_Adipose_Visceral_Omentum_0.5.db", "TW_Adrenal_Gland_0.5.db", "TW_Artery_Aorta_0.5.db", "TW_Artery_Coronary_0.5.db", "TW_Artery_Tibial_0.5.db", "TW_Brain_Anterior_cingulate_cortex_BA24_0.5.db", "TW_Brain_Caudate_basal_ganglia_0.5.db", "TW_Brain_Cerebellar_Hemisphere_0.5.db", "TW_Brain_Cerebellum_0.5.db", "TW_Brain_Cortex_0.5.db", "TW_Brain_Frontal_Cortex_BA9_0.5.db", "TW_Brain_Hippocampus_0.5.db", "TW_Brain_Hypothalamus_0.5.db", "TW_Brain_Nucleus_accumbens_basal_ganglia_0.5.db", "TW_Brain_Putamen_basal_ganglia_0.5.db", "TW_Breast_Mammary_Tissue_0.5.db", "TW_Cells_EBV-transformed_lymphocytes_0.5.db", "TW_Cells_Transformed_fibroblasts_0.5.db", "TW_Colon_Sigmoid_0.5.db", "TW_Colon_Transverse_0.5.db", "TW_Esophagus_Gastroesophageal_Junction_0.5.db", "TW_Esophagus_Mucosa_0.5.db", "TW_Esophagus_Muscularis_0.5.db", "TW_Heart_Atrial_Appendage_0.5.db", "TW_Heart_Left_Ventricle_0.5.db", "TW_Liver_0.5.db", "TW_Lung_0.5.db", "TW_Muscle_Skeletal_0.5.db", "TW_Nerve_Tibial_0.5.db", "TW_Ovary_0.5.db", "TW_Pancreas_0.5.db", "TW_Pituitary_0.5.db", "TW_Prostate_0.5.db", "TW_Skin_Not_Sun_Exposed_Suprapubic_0.5.db", "TW_Skin_Sun_Exposed_Lower_leg_0.5.db", "TW_Small_Intestine_Terminal_Ileum_0.5.db", "TW_Spleen_0.5.db", "TW_Stomach_0.5.db", "TW_Testis_0.5.db", "TW_Thyroid_0.5.db", "TW_Uterus_0.5.db", "TW_Vagina_0.5.db", "TW_Whole_Blood_0.5.db")
threshold <- 0.05

significant<-fread("/home/peter/PrediXcan/significant.txt")
for(i in database_tissues){
		PrediXcan_result <- fread("/home/peter/PrediXcan/PrediXcanOutput/AA_" %&% i %&% "_association.txt")
		PrediXcan_result$FDR <- p.adjust(PrediXcan_result$p)
		fwrite(PrediXcan_result, "/home/peter/PrediXcan/FDR/" %&% i %&% "_association_FDR.txt", sep = "\t")
		PrediXcan_result$tissue <- i
		PrediXcan_result <- subset(PrediXcan_result, FDR <= threshold)
		significant <- bind_rows(significant, PrediXcan_result)
	}

fwrite(significant, "/home/peter/PrediXcan/significant.txt")

```

```{r}
genenames<-fread("/home/peter/PrediXcan/BP_Chrome.txt", header=T)

Hypothalamus_Names<-left_join(Brain_HypothalamusAssoc,genenames, by=c("gene"))
Hypothalamus_Names<-mutate(Hypothalamus_Names,gene,beta,z,p,'se(beta)',CHR=as.numeric(Hypothalamus_Names$CHR),BP,gene_name)
```

